// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgNI9TexoBzKPrn3dtB3y3loqjVxr8zzw',
    appId: '1:591748402340:web:19efd239b5a99c390faa31',
    messagingSenderId: '591748402340',
    projectId: 'leafscan-c97b0',
    authDomain: 'leafscan-c97b0.firebaseapp.com',
    storageBucket: 'leafscan-c97b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFWpNwaPQQx_HeAsmhqvN-p_ljBRV-uXI',
    appId: '1:591748402340:android:1dad80c918a991c70faa31',
    messagingSenderId: '591748402340',
    projectId: 'leafscan-c97b0',
    storageBucket: 'leafscan-c97b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuQhQkrfwNyq64JchUU21uJsIS5t4iJdo',
    appId: '1:591748402340:ios:03ed4f6c260466240faa31',
    messagingSenderId: '591748402340',
    projectId: 'leafscan-c97b0',
    storageBucket: 'leafscan-c97b0.firebasestorage.app',
    iosBundleId: 'com.example.leafScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuQhQkrfwNyq64JchUU21uJsIS5t4iJdo',
    appId: '1:591748402340:ios:03ed4f6c260466240faa31',
    messagingSenderId: '591748402340',
    projectId: 'leafscan-c97b0',
    storageBucket: 'leafscan-c97b0.firebasestorage.app',
    iosBundleId: 'com.example.leafScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgNI9TexoBzKPrn3dtB3y3loqjVxr8zzw',
    appId: '1:591748402340:web:1e6b7d987f167f850faa31',
    messagingSenderId: '591748402340',
    projectId: 'leafscan-c97b0',
    authDomain: 'leafscan-c97b0.firebaseapp.com',
    storageBucket: 'leafscan-c97b0.firebasestorage.app',
  );
}
